Web/PatniListi.Web/Controllers/ContactsController.cs
namespace PatniListi.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PatniListi.Common;
    using PatniListi.Data.Common.Repositories;
    using PatniListi.Data.Models;
    using PatniListi.Services.Messaging;
    using PatniListi.Web.ViewModels.Models.Contacts;

    public class ContactsController : BaseController
    {
        private readonly IRepository<ContactFormEntry> contactsRepository;
        private readonly IEmailSender emailSender;

        public ContactsController(IRepository<ContactFormEntry> contactsRepository, IEmailSender emailSender)
        {
            this.contactsRepository = contactsRepository;
            this.emailSender = emailSender;
        }

        public IActionResult Contact()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Contact(ContactFormViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var ip = this.HttpContext.Connection.RemoteIpAddress.ToString();

            var viewModel = new ContactFormEntry
            {
                FullName = input.FullName,
                Email = input.Email,
                Title = input.Title,
                Content = input.Content,
                Ip = ip,
            };

            await this.contactsRepository.AddAsync(viewModel);
            await this.contactsRepository.SaveChangesAsync();

            await this.emailSender.SendEmailAsync(
                input.Email, input.FullName, GlobalConstants.SystemEmail, input.Title, input.Content);

            return this.RedirectToAction("ThankYou");
        }

        [Authorize]
        public IActionResult ThankYou()
        {
            return this.View();
        }
    }
}

Web/PatniListi.Web/Views/Shared/NotFound.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">

    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

</head>

<body>
    <section class="py-5">
        <div class="container shadow py-4 px-4">
            <div id="notfound">
                <div class="notfound">
                    <div class="notfound-404">
                        <h1 class="text-primary">404</h1>
                    </div>
                    <h2 class="text-white">За съжаление страницата, която търсите не може да бъде намерена!</h2>

                    <hr />

                    <a href="/"><span class="arrow"></span>Начало</a>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

Web/PatniListi.Web/Views/Shared/_CompanyEditPartial.cshtml
@using Microsoft.AspNetCore.Http.Features
@using PatniListi.Data.Models
@using PatniListi.Common
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager

@if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
{
        <a type="button" id="hideButton" class="btn btn-primary btn-block" asp-area="Administration" asp-controller="Companies" asp-action="Edit" asp-route-id="@this.UserManager.GetUserAsync(User).Result?.CompanyId">Моля, завършете регистрацията на фирмата.</a>
}

Web/PatniListi.Web/Views/Shared/_Layout.cshtml
@using PatniListi.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/favicon.png">
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>

    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- Nucleo Icons -->
    <link href="~/assets/css/nucleo-icons.css" rel="stylesheet" />
    <!-- CSS Files -->
    <link href="~/assets/css/blk-design-system.css?v=1.0.0" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-transparent" color-on-scroll="100">
            <div class="container">
                <div class="navbar-translate">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                    <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar bar2"></span>
                        <span class="navbar-toggler-bar bar2"></span>
                        <span class="navbar-toggler-bar bar2"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse justify-content-end" id="navigation">

                    <div class="navbar-collapse-header">
                        <div class="row">
                            <div class="col-6 collapse-brand">
                                <a>
                                    @GlobalConstants.SystemName
                                </a>
                            </div>
                            <div class="col-6 collapse-close text-right">
                                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                                    <i class="tim-icons icon-simple-remove"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>

                        <partial name="_NavBarPartial" />
                    </ul>
                    <ul class="navbar-nav">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <div>
            <partial name="_CookieConsentPartial" />
        </div>
        <br />

        <main role="main" class="p-3">
            <div>
                @this.RenderBody()

            </div>
        </main>
    </div>

    <footer class="footer">
        <div class="row">
            <div class="col-sm-4">
                <h3 class="title">&copy; @DateTime.Now.Year - @GlobalConstants.SystemName</h3>
            </div>

            <div class="col-sm-4">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Guidance">Ръководство</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Поверителност</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Contacts" asp-action="Contact">Контакти</a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-4">
                <h3 class="title">Последвайте ни:</h3>
                <div class="btn-wrapper profile">
                    <a target="_blank" href="https://twitter.com/creativetim" class="btn btn-icon btn-neutral btn-round btn-simple" data-toggle="tooltip" data-original-title="Follow us">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a target="_blank" href="https://www.facebook.com/creativetim" class="btn btn-icon btn-neutral btn-round btn-simple" data-toggle="tooltip" data-original-title="Like us">
                        <i class="fab fa-facebook-square"></i>
                    </a>
                    <a target="_blank" href="https://dribbble.com/creativetim" class="btn btn-icon btn-neutral  btn-round btn-simple" data-toggle="tooltip" data-original-title="Follow us">
                        <i class="fab fa-dribbble"></i>
                    </a>
                </div>
            </div>
        </div>

        <!-- Return to Top -->
        <a href="javascript:" id="return-to-top"><i class="icon-chevron-up"></i></a>

        <!-- ICON NEEDS FONT AWESOME FOR CHEVRON UP ICON -->
        <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <!--   Core JS Files   -->
    <script src="~/assets/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="~/assets/js/core/popper.min.js" type="text/javascript"></script>
    <script src="~/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
    <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
    <script src="~/assets/js/plugins/bootstrap-switch.js"></script>
    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="~/assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
    <!-- Chart JS -->
    <script src="~/assets/js/plugins/chartjs.min.js"></script>
    <!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
    <script src="~/assets/js/plugins/moment.min.js"></script>
    <script src="~/assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>
    <!-- Control Center for Black UI Kit: parallax effects, scripts for the example pages etc -->
    <script src="~/assets/js/blk-design-system.min.js?v=1.0.0" type="text/javascript"></script>

    <script>
        $(document).ready(function () {
            blackKit.initDatePicker();
            blackKit.initSliders();


            /* This is change event for your dropdownlist */
            $('#allRoutes').change( function () {

                /* Get the selected value of dropdownlist */
                var selectedIds = $(this).val();

                /* Request the partial view with .get request. */
                $.get('/TransportWorkTickets/RouteDetailsPartial/' + selectedIds, function (data) {

                    /* data is the pure html returned from action method, load it to your page */
                    $('#partialPlaceHolder').html(data);
                    /* little fade in effect */
                    $('#partialPlaceHolder').fadeIn('fast');
                }).done(function () {
                    if ($('#totalDistance').length)
                        $('#travelledDistance').val($('#totalDistance').html());

                    $('#startKilometers').val(Number($('#carStartKilometers').val()) + Number($('#allTravelledDistance').val()));

                    $('#fuelAvailability').val(((Number($('#carInitialFuel').val()) + Number($('#allLiters').val())) - Number($('#allFuelConsumption').val())).toFixed(2));

                    $('#endKilometers').val((Number($('#startKilometers').val()) + Number($('#travelledDistance').val())).toFixed(2));

                    $('#fuelConsumption').val((Number($('#travelledDistance').val()) * (Number($('#carAverageConsumption').val()) / 100.00)).toFixed(2));

                    $('#residue').val((Number($('#fuelAvailability').val()) - Number($('#fuelConsumption').val())).toFixed(2));
                });
            });

            $('#carModel').change(function () {

                /* Get the selected value of dropdownlist */
                var selectedId = $(this).val();

                /* Request the partial view with .get request. */
                $.get('/InvoiceReports/InvoiceReportsPartial/' + selectedId, function (data) {

                    /* data is the pure html returned from action method, load it to your page */
                    $('#partialInvoicePlaceHolder').html(data);
                    /* little fade in effect */
                    $('#partialInvoicePlaceHolder').fadeIn('fast');
                })
            });
        });

        function scrollToDownload() {

            if ($('.section-download').length != 0) {
                $("html, body").animate({
                    scrollTop: $('.section-download').offset().top
                }, 1000);
            }
        }
    </script>

    <script>
        // ===== Scroll to Top ====
        $(window).scroll(function () {
            if ($(this).scrollTop() >= 50) {        // If page is scrolled more than 50px
                $('#return-to-top').fadeIn(200);    // Fade in the arrow
            } else {
                $('#return-to-top').fadeOut(200);   // Else fade out the arrow
            }
        });
        $('#return-to-top').click(function () {      // When arrow is clicked
            $('body,html').animate({
                scrollTop: 0                       // Scroll to top of body
            }, 500);
        });
    </script>


<script>

    function GetTotalPrice() {
        var number1 = parseFloat(document.getElementById("Number1").value);
        var number2 = parseFloat(document.getElementById("Number2").value);
        var sum = number1 * number2;
        document.getElementById("ResultNumber").value = roundToTwo(sum);

    }

    function roundToTwo(num) {
        return +(Math.round(num + "e+2") + "e-2");
    }

    $(function () {
        moment.locale("bg");
        $("time").each(function (i, e) {
            var dateTimeValue = $(e).attr("datetime");
            if (!dateTimeValue) {
                return;
            }

            var time = moment.utc(dateTimeValue).local();
            $(e).html(time.format("llll"));
            $(e).attr("title", $(e).attr("datetime"));
        });
    });
</script>

@this.RenderSection("Scripts", required: false)

</body>
</html>

Web/PatniListi.Web/Views/Shared/_NavBarPartial.cshtml
@using PatniListi.Data.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (!this.SignInManager.IsSignedIn(this.User))
{
    <li class="nav-item">
        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Guidance">Ръководство</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Поверителност</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-area="" asp-controller="Contacts" asp-action="Contact">Контакти</a>
    </li>
}

Web/PatniListi.Web/Views/Shared/_RouteDetailsPartial.cshtml
@using PatniListi.Data.Models
@using Microsoft.AspNetCore.Identity
@using PatniListi.Services.Data
@using PatniListi.Web.ViewModels.Models.Routes
@inject IRoutesService routesService
@inject UserManager<ApplicationUser> UserManager
@model PatniListi.Web.ViewModels.Models.TransportWorkTickets.TransportWorkTicketInputViewModel

    <table class="table table-responsive-md table-hover">
        <tr class="text-white">
            <th>
                Маршрут
            </th>
            <th>
                Разстояние
            </th>
            <th>

            </th>
            <th>

            </th>
            <th>

            </th>
        </tr>
        @foreach (var route in Model.Routes)
        {
            <tr>
            <td>
                @route.Route
            </td>
            <td>
                @route.Distance
            </td>
            <td>

            </td> 
            <td>

            </td>
            <td>

            </td>
        </tr>
        }

        <tfoot>
            @{
                var TotalDistance = Model.Routes.Select(r => r.Distance).Sum();
            }
            <tr>
                <td>Общо:</td>
                <td id="totalDistance">@TotalDistance</td>
                <td>

                </td>
                <td>

                </td>
                <td>

                </td>
            </tr>
        </tfoot>
    </table>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}