Web/PatniListi.Web/Areas/Administration/Controllers/TransportWorkTicketsController.cs
namespace PatniListi.Web.Areas.Administration.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using PatniListi.Common;
    using PatniListi.Data.Models;
    using PatniListi.Services.Data;
    using PatniListi.Web.Infrastructure;
    using PatniListi.Web.ViewModels.Administration.Cars;
    using PatniListi.Web.ViewModels.Administration.TransportWorkTickets;
    using PatniListi.Web.ViewModels.Administration.Users;
    using PatniListi.Web.ViewModels.Models.Routes;

    public class TransportWorkTicketsController : AdministrationController
    {
        private readonly ITransportWorkTicketsService transportWorkTicketsService;
        private readonly ICarsService carsService;
        private readonly IUsersService usersService;
        private readonly IRoutesService routesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IRouteTransportWorkTicketsService routeTransportWorkTicketsService;

        public TransportWorkTicketsController(ITransportWorkTicketsService transportWorkTicketsService, ICarsService carsService, IUsersService usersService, IRoutesService routesService, UserManager<ApplicationUser> userManager, IRouteTransportWorkTicketsService routeTransportWorkTicketsService)
        {
            this.transportWorkTicketsService = transportWorkTicketsService;
            this.carsService = carsService;
            this.usersService = usersService;
            this.routesService = routesService;
            this.userManager = userManager;
            this.routeTransportWorkTicketsService = routeTransportWorkTicketsService;
        }

        public async Task<IActionResult> All(string id, int? pageNumber)
        {
            this.TempData["carId"] = id;

            if (id == null)
            {
                return this.NotFound();
            }

            var workTickets = this.transportWorkTicketsService
                .GetAll<TransportWorkTicketViewModel>(id);

            return this.View(await PaginatedList<TransportWorkTicketViewModel>.CreateAsync(workTickets, pageNumber ?? GlobalConstants.DefaultPageNumber, GlobalConstants.PageSize));
        }

        public async Task<IActionResult> Create()
        {
            var id = this.TempData.Peek("carId").ToString();

            var carFromDb = await this.carsService.GetDetailsAsync<CarDetailsViewModel>(id);
            var viewModel = new TransportWorkTicketInputViewModel
            {
                CarId = carFromDb.Id,
                CarFuelType = carFromDb.FuelType,
                CarModel = carFromDb.Model,
                CarCompanyId = carFromDb.CompanyId,
                CarAverageConsumption = carFromDb.AverageConsumption,
                CarInitialFuel = carFromDb.InitialFuel,
                CarLicensePlate = carFromDb.LicensePlate,
                CarStartKilometers = carFromDb.StartKilometers,
                CarTankCapacity = carFromDb.TankCapacity,
                AllDrivers = this.usersService.GetAll(carFromDb.CompanyId),
                AllLiters = this.carsService.GetCurrentLitresByCarId(carFromDb.Id),
                AllTravelledDistance = this.carsService.GetCurrentTravelledDistanceByCarId(carFromDb.Id),
                AllFuelConsumption = this.carsService.GetCurrentFuelConsumptionByCarId(carFromDb.Id),
                AllRoutes = this.routesService.GetAll(),
            };

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TransportWorkTicketInputViewModel input)
        {
            var id = this.TempData.Peek("carId").ToString();

            if (!this.ModelState.IsValid)
            {
                input.AllDrivers = this.usersService.GetUsersByCar(input.CarId);
                input.AllLiters = this.carsService.GetCurrentLitresByCarId(input.CarId);
                input.AllTravelledDistance = this.carsService.GetCurrentTravelledDistanceByCarId(input.CarId);
                input.AllFuelConsumption = this.carsService.GetCurrentFuelConsumptionByCarId(input.CarId);
                input.AllRoutes = this.routesService.GetAll();

                return this.View(input);
            }

            var user = await this.usersService.GetByNameAsync<UserViewModel>(input.ApplicationUserFullName, input.CarCompanyId);

            var transportWorkTicket = await this.transportWorkTicketsService.CreateAsync(input.Date, user.Id, input.CarId, input.CreatedBy, input.StartKilometers, input.EndKilometers, input.FuelConsumption, input.Residue, input.FuelAvailability, input.TravelledDistance);
            await this.routeTransportWorkTicketsService.UpdateAsync(transportWorkTicket.Id, input.CarCompanyId, input.Route);

            return this.RedirectToAction("All", "TransportWorkTickets", new { id });
        }

        public async Task<IActionResult> Details(string id)
        {
            var viewModel = await this.transportWorkTicketsService
                .GetDetailsAsync<TransportWorkTicketDetailsViewModel>(id);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var viewModel = await this.transportWorkTicketsService.GetDetailsAsync<TransportWortkTicketEditViewModel>(id);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            viewModel.AllDrivers = this.usersService.GetAll(viewModel.CarCompanyId);
            viewModel.AllLiters = this.carsService.GetCurrentLitresByCarId(viewModel.CarId);
            viewModel.AllTravelledDistance = this.carsService.GetCurrentTravelledDistanceByCarId(viewModel.CarId, viewModel.Id);
            viewModel.AllFuelConsumption = this.carsService.GetCurrentFuelConsumptionByCarId(viewModel.CarId, viewModel.Id);
            viewModel.AllRoutes = this.routesService.GetAll();

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TransportWortkTicketEditViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                var viewModel = await this.transportWorkTicketsService.GetDetailsAsync<TransportWortkTicketEditViewModel>(input.Id);

                viewModel.AllDrivers = this.usersService.GetUsersByCar(viewModel.CarId);
                viewModel.AllLiters = this.carsService.GetCurrentLitresByCarId(viewModel.CarId);
                viewModel.AllTravelledDistance = this.carsService.GetCurrentTravelledDistanceByCarId(viewModel.CarId, viewModel.Id);
                viewModel.AllFuelConsumption = this.carsService.GetCurrentFuelConsumptionByCarId(viewModel.CarId, viewModel.Id);
                viewModel.AllRoutes = this.routesService.GetAll();

                return this.View(viewModel);
            }

            var user = await this.usersService.GetByNameAsync<UserDetailsViewModel>(input.ApplicationUserFullName, input.CarCompanyId);

            await this.transportWorkTicketsService.EditAsync(input.Id, input.CreatedOn, input.Date, user.Id, input.CarId, input.CreatedBy, input.ModifiedBy, input.StartKilometers, input.EndKilometers, input.FuelConsumption, input.Residue, input.FuelAvailability, input.TravelledDistance);
            await this.routeTransportWorkTicketsService.UpdateAsync(input.Id, input.CarCompanyId, input.Route);

            return this.RedirectToAction("All", "TransportWorkTickets", new { id = input.CarId });
        }

        public async Task<IActionResult> Delete(string id)
        {
            var viewModel = await this.transportWorkTicketsService.GetDetailsAsync<TransportWorkTicketDeleteViewModel>(id);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> ConfirmDelete(string id)
        {
            var carId = this.TempData.Peek("carId").ToString();
            var currentUserFullname = this.userManager.GetUserAsync(this.User).Result?.FullName;

            var deleted = await this.transportWorkTicketsService.DeleteAsync(id, currentUserFullname);

            if (!deleted)
            {
                return this.NotFound();
            }

            await this.routeTransportWorkTicketsService.SetIsDeletedAsync(id, currentUserFullname);
            return this.RedirectToAction("All", "TransportWorkTickets", new { id = carId });
        }

        public async Task<ActionResult> RouteDetailsPartial(string id)
        {
            var viewModel = new TransportWorkTicketInputViewModel();
            viewModel.Routes = new List<RouteViewModel>();

            string[] splittedIds = id.Split(",", System.StringSplitOptions.RemoveEmptyEntries);

            foreach (var routeId in splittedIds)
            {
                var currentRoute = await this.routesService.GetByIdAsync<RouteViewModel>(routeId);
                viewModel.Routes.Add(currentRoute);
            }

            return this.PartialView("_RouteDetailsPartial", viewModel);
        }
    }
}

Web/PatniListi.Web/Controllers/CarsController.cs
namespace PatniListi.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using PatniListi.Common;
    using PatniListi.Data.Models;
    using PatniListi.Services.Data;
    using PatniListi.Web.Infrastructure;
    using PatniListi.Web.ViewModels.Models.Cars;

    [Authorize]
    public class CarsController : BaseController
    {
        private readonly ICarsService carsService;
        private readonly UserManager<ApplicationUser> userManager;

        public CarsController(ICarsService carsService, UserManager<ApplicationUser> userManager)
        {
            this.carsService = carsService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> All(int? pageNumber)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var cars = this.carsService
                .GetCarsByUser<CarViewModel>(user.Id, user.CompanyId);

            return this.View(await PaginatedList<CarViewModel>.CreateAsync(cars, pageNumber ?? GlobalConstants.DefaultPageNumber, GlobalConstants.PageSize));
        }

        public async Task<IActionResult> Details(string id)
        {
            var viewModel = await this.carsService
                .GetDetailsAsync<CarDetailsViewModel>(id);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }
    }
}

Web/PatniListi.Web/Areas/Administration/Views/TransportWorkTickets/All.cshtml
@using  PatniListi.Web.Infrastructure;
@model PaginatedList<PatniListi.Web.ViewModels.Administration.TransportWorkTickets.TransportWorkTicketViewModel>

@{
    ViewData["Title"] = "Пътни листи";
}

    <section class="py-5">
        <div class="container shadow py-4 px-4">
            <h1 class="text-center">@ViewData["Title"]</h1>
            <div>
                <a class="nav-link btn btn-primary btn-block text-uppercase" asp-area="Administration" asp-controller="TransportWorkTickets" asp-action="Create">Добави пътен лист</a>

                <div>
                    <div class="clearfix"></div>
                    @if (Model.TotalPages != 0)
                    {
                        if (!Model.PreviousDisabled)
                        {
                            <div class="float-md-left">
                                <a asp-action="All"
                                   asp-route-pageNumber="@Model.PreviousPage"
                                   class="button">
                                    Предишна
                                </a>
                            </div>
                        }

                        if (!Model.NextDisabled)
                        {
                            <div class="float-md-right">
                                <a asp-action="All"
                                   asp-route-pageNumber="@Model.NextPage"
                                   class="button">
                                    Следваща
                                </a>
                            </div>
                        }
                    }
                </div>
            </div>

            <br />
            <br />

            <table class="table table-responsive-md table-hover">
                <tr class="text-white">
                    <th>
                        Дата на тръгване
                    </th>
                    <th>
                        Автомобил
                    </th>
                    <th>
                        Шофьор
                    </th>
                    <th>
                        Изминати километри
                    </th>
                    <th>

                    </th>
                </tr>
                @for (int i = 0; i < Model.Count; i++)
                {
                    <tr>
                        <td>
                            @Model[i].Date.ToShortDateString()
                        </td>
                        <td>
                            @Model[i].Car
                        </td>
                        <td>
                            @Model[i].ApplicationUserFullName
                        </td>
                        <td>
                            @Model[i].TravelledDistance.ToString("F2")
                        </td>
                        <td class="text-center">
                            <div>
                                <a href="/Administration/TransportWorkTickets/Details/@Model[i].Id" class="justify-content-md-between">Детайли</a>
                            </div>
                            <div>
                                <a href="/Administration/TransportWorkTickets/Edit/@Model[i].Id" class="justify-content-md-between">Промени</a>
                            </div>
                            @if (Model[i] == Model[Model.Count - 1])
                            {
                                <div>
                                    <a href="/Administration/TransportWorkTickets/Delete/@Model[i].Id" class="justify-content-md-between">Изтрий</a>
                                </div>
                            }
                        </td>
                    </tr>
                }
            </table>

            <div class="form-group text-center">
                <div class="button-holder">
                    <a asp-area="Administration" asp-controller="Cars" asp-action="All" class="text-uppercase">Автомобили</a>
                </div>
            </div>
        </div>
     </section>

Web/PatniListi.Web/Areas/Administration/Views/TransportWorkTickets/Create.cshtml
@using PatniListi.Data.Models
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model PatniListi.Web.ViewModels.Administration.TransportWorkTickets.TransportWorkTicketInputViewModel

@{
    ViewData["Title"] = $"Добави пътен лист за {Model.CarModel}";
}

<section class="py-5">
    <div class="container shadow py-4 px-4">
        <h1 class="text-center">@ViewData["Title"]</h1>
        <div class="card-body">
            <form asp-area="Administration" asp-controller="TransportWorkTickets" asp-action="Create" method="post">
                <br />
                <fieldset>
                    <legend class="text-white">Основни данни: </legend>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="ApplicationUserFullName"></label>
                                <select asp-for="ApplicationUserFullName" asp-items="Model.AllDrivers" class="form-control">
                                    <option selected="selected" value="" disabled>--Моля, изберете--</option>
                                </select>
                                <span asp-validation-for="AllDrivers" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Date"></label>
                                <input asp-for="Date" type="text" id="datepicker" class="form-control datepicker" value="@DateTime.UtcNow.ToShortDateString()" />
                                <span asp-validation-for="Date" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="Car"></label>
                                <input asp-for="Car" readonly class="form-control text-white" value="@Model.Car" />
                                <span asp-validation-for="Car" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="CarFuelType"></label>
                                <input asp-for="CarFuelType" readonly class="form-control text-white" value="@Model.CarFuelType" />
                                <span asp-validation-for="CarFuelType" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="CarAverageConsumption"></label>
                                <input asp-for="CarAverageConsumption" id="carAverageConsumption" readonly class="form-control text-white" value="@Model.CarAverageConsumption" />
                                <span asp-validation-for="CarAverageConsumption" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="CreatedBy"></label>
                                <input asp-for="CreatedBy" type="text" readonly class="form-control text-white" value="@this.UserManager.GetUserAsync(this.User).Result?.FullName" />
                                <span asp-validation-for="CreatedBy" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <br />

                <fieldset>
                    <legend class="text-white">Mаршрути: </legend>
                    <div class="row">
                        <div class="col-md-12">
                            <label asp-for="Route"></label>
                            <select asp-for="Route" asp-items="Model.AllRoutes" id="allRoutes" class="form-control">
                                <option selected="selected" value="" disabled>--Моля, изберете--</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label></label>
                            <div class="button-holder">
                                <a class="nav-link btn btn-primary btn-block text-uppercase" asp-area="" asp-controller="Routes" asp-action="Create">Създай маршрут</a>
                            </div>
                        </div>
                    </div>
                    <div id="partialPlaceHolder" style="display:none;">
                    </div>
                </fieldset>
                <br />

                <fieldset>
                    <legend class="text-white">Километраж: </legend>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="StartKilometers"></label>
                                <input asp-for="StartKilometers" id="startKilometers" readonly class="form-control text-white" />
                                <span asp-validation-for="StartKilometers" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label asp-for="TravelledDistance"></label>
                            <input asp-for="TravelledDistance" id="travelledDistance" readonly class="form-control text-white" />
                            <span asp-validation-for="TravelledDistance" class="text-danger"></span>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="EndKilometers"></label>
                                <input asp-for="EndKilometers" id="endKilometers" readonly class="form-control text-white" />
                                <span asp-validation-for="EndKilometers" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <br />

                <fieldset>
                    <legend class="text-white">Гориво: </legend>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="FuelAvailability"></label>
                                <input asp-for="FuelAvailability" id="fuelAvailability" readonly class="form-control text-white" value="@Model.FuelAvailability.ToString("F2")" />
                                <span asp-validation-for="FuelAvailability" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="FuelConsumption"></label>
                                <input asp-for="FuelConsumption" id="fuelConsumption" readonly class="form-control text-white" value="@Model.FuelConsumption" />
                                <span asp-validation-for="FuelConsumption" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="Residue" class="text-md-left"></label>
                                <input asp-for="Residue" id="residue" readonly class="form-control text-white" value="@Model.Residue" />
                                <span asp-validation-for="Residue" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <input type="hidden" asp-for="CarId" readonly class="form-control" value="@Model.CarId" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <input type="hidden" asp-for="CarCompanyId" readonly class="form-control" value="@Model.CarCompanyId" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <input type="hidden" asp-for="CarStartKilometers" id="carStartKilometers" readonly class="form-control" value="@Model.CarStartKilometers" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <input type="hidden" asp-for="AllTravelledDistance" id="allTravelledDistance" readonly class="form-control" value="@Model.AllTravelledDistance" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <input type="hidden" asp-for="AllLiters" id="allLiters" readonly class="form-control" value="@Model.AllLiters" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <input type="hidden" asp-for="CarInitialFuel" id="carInitialFuel" readonly class="form-control" value="@Model.CarInitialFuel" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <input type="hidden" asp-for="AllFuelConsumption" id="allFuelConsumption" readonly class="form-control" value="@Model.AllFuelConsumption" />
                            </div>
                        </div>
                    </div>
                </fieldset>
                <br />

                <div class="form-group text-center">
                    <div class="button-holder">
                        <button type="submit" class="btn btn-primary btn-block text-uppercase">Добави</button>
                        <a class="nav-link text-uppercase text-center" asp-area="Administration" asp-controller="TransportWorkTickets" asp-action="All" asp-route-id="@Model.CarId">Пътни листи</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}