Web/PatniListi.Web/Controllers/InvoiceReportsController.cs
namespace PatniListi.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using PatniListi.Data.Models;
    using PatniListi.Services.Data;
    using PatniListi.Web.ViewModels.Models.InvoiceReports;

    [Authorize]
    public class InvoiceReportsController : BaseController
    {
        private readonly ICarsService carsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IInvoicesService invoicesService;

        public InvoiceReportsController(ICarsService carsService, UserManager<ApplicationUser> userManager, IInvoicesService invoicesService)
        {
            this.carsService = carsService;
            this.userManager = userManager;
            this.invoicesService = invoicesService;
        }

        public async Task<IActionResult> Index()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var viewModel = new InvoiceReportsIndexViewModel();

            if (this.User.IsInRole("Admin"))
            {
                viewModel.AllCars = this.carsService.GetAll(user.CompanyId);
            }
            else
            {
                viewModel.AllCars = this.carsService.GetAllCarsByUserId(user.Id, user.CompanyId);
            }

            return this.View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Index(InvoiceReportsIndexViewModel viewModel)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            if (this.User.IsInRole("Admin"))
            {
                viewModel.AllCars = this.carsService.GetAll(user.CompanyId);
            }
            else
            {
                viewModel.AllCars = this.carsService.GetAllCarsByUserId(user.Id, user.CompanyId);
            }

            viewModel.Invoices = this.invoicesService.GetAllInvoicesForPeriod<InvoiceReportsViewModel>(viewModel.CarId, viewModel.From, viewModel.To);

            if (!this.ModelState.IsValid)
            {
                return this.View(viewModel);
            }

            return this.View("Index", viewModel);
        }
    }
}

Web/PatniListi.Web/Views/InvoiceReports/Index.cshtml
@using PatniListi.Data.Models
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model PatniListi.Web.ViewModels.Models.InvoiceReports.InvoiceReportsIndexViewModel

@{
    ViewData["Title"] = $"Справка фактури";
}

<section class="py-5">
    <div class="container shadow py-4 px-4">
        <h1 class="text-center">@ViewData["Title"]</h1>
        <div class="card-body">
            <form asp-area="" asp-controller="InvoiceReports" asp-action="Index" method="get">
                <br />
                <fieldset>
                    <legend class="text-white">Фактури: </legend>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="From"></label>
                                <input asp-for="From" type="text" id="datepicker" class="form-control datepicker" value="@(Model.From > DateTime.MinValue ? Model.From.ToShortDateString() : DateTime.UtcNow.ToShortDateString())"/>
                                <span asp-validation-for="From" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="To"></label>
                                <input asp-for="To" type="text" id="datepicker" class="form-control datepicker" value="@(Model.To > DateTime.MinValue ? Model.To.ToShortDateString() : DateTime.UtcNow.ToShortDateString())" />
                                <span asp-validation-for="To" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="CarId"></label>
                                <select asp-for="CarId" asp-items="@Model.AllCars" id="carModel" class="form-control">
                                    <option selected="selected" value="@Model.CarId" disabled>--Моля, изберете--</option>
                                </select>
                                <span asp-validation-for="AllCars" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label></label>
                            <div class="button-holder">
                                <input type="submit" value="Покажи резултати" class="btn btn-primary btn-block text-uppercase" /> 
                            </div>
                        </div>
                    </div>
                    <br />
                    <br />

                    <div class="row">
                        <div id="content" class="col-md-12">

                            <table class="table table-responsive-md table-hover">
                                <tr class="text-white text-center">
                                    <th>
                                        Номер
                                    </th>
                                    <th>
                                        Дата
                                    </th>
                                    <th>
                                        Автомобил
                                    </th>
                                    <th>
                                        Гориво
                                    </th>
                                    <th>
                                        Литри
                                    </th>
                                    <th>
                                        Цена
                                    </th>
                                    <th>
                                        Стойност
                                    </th>
                                    <th>
                                        От град
                                    </th>
                                    <th>
                                        Въведена на
                                    </th>
                                </tr>
                                @foreach (var invoice in Model.Invoices)
                                {
                                    <tr class="text-white text-center">
                                        <td>
                                            @invoice.Number
                                        </td>
                                        <td>
                                            @invoice.Date.ToShortDateString()
                                        </td>
                                        <td>
                                            @invoice.Car
                                        </td>
                                        <td>
                                            @invoice.CarFuelType
                                        </td>
                                        <td>
                                            @invoice.Quantity
                                        </td>
                                        <td>
                                            @invoice.Price
                                        </td>
                                        <td>
                                            @invoice.TotalPrice
                                        </td>
                                        <td>
                                            @invoice.Location
                                        </td>
                                        <td>
                                            @invoice.CreatedOn.ToShortDateString()
                                        </td>
                                    </tr>
                                }

                                <tfoot>
                                    @{
                                        var TotalQuantity = Model.Invoices.Select(i => i.Quantity).Sum();
                                        var TotalSum = Model.Invoices.Select(i => i.TotalPrice).Sum();
                                    }
                                    <tr class="text-white text-center">
                                        <th class="text-white" colspan="3"></th>
                                        <th class="text-white" colspan="1">Общо литри:</th>
                                        <td id="invoiceTotalLiters">@TotalQuantity</td>

                                        <th class="text-white" colspan="1">Обща сума:</th>
                                        <td id="invoiceTotalSum">@TotalSum</td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </fieldset>
                <br />

            </form>
        </div>
    </div>
</section>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}